/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class calculatrice extends javax.swing.JFrame {

    private double num1, num2;
    private String op;
    
    public calculatrice() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Ecran = new javax.swing.JTextField();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bVirg = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        bAc = new javax.swing.JButton();
        bX = new javax.swing.JButton();
        bDiv = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        bSous = new javax.swing.JButton();
        bAns = new javax.swing.JButton();
        bEgal = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        bX2 = new javax.swing.JButton();
        bXn = new javax.swing.JButton();
        bLog = new javax.swing.JButton();
        bLn = new javax.swing.JButton();
        bTan = new javax.swing.JButton();
        bCos = new javax.swing.JButton();
        bSin = new javax.swing.JButton();
        bParen1 = new javax.swing.JButton();
        bParen2 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        jButton5.setText("7");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        Ecran.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        Ecran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcranActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(204, 204, 204));
        b7.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b7.setText("7");
        b7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(204, 204, 204));
        b8.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b8.setText("8");
        b8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(204, 204, 204));
        b9.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b9.setText("9");
        b9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(204, 204, 204));
        b4.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b4.setText("4");
        b4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(204, 204, 204));
        b5.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b5.setText("5");
        b5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(204, 204, 204));
        b6.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b6.setText("6");
        b6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(204, 204, 204));
        b1.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b1.setText("1");
        b1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(204, 204, 204));
        b2.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b2.setText("2");
        b2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(204, 204, 204));
        b3.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b3.setText("3");
        b3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(204, 204, 204));
        b0.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        b0.setText("0");
        b0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bVirg.setBackground(new java.awt.Color(204, 204, 204));
        bVirg.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bVirg.setText(".");
        bVirg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bVirg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVirgActionPerformed(evt);
            }
        });

        bDel.setBackground(new java.awt.Color(255, 153, 51));
        bDel.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bDel.setText("DEL");
        bDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bAc.setBackground(new java.awt.Color(255, 153, 51));
        bAc.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bAc.setText("AC");
        bAc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcActionPerformed(evt);
            }
        });

        bX.setBackground(new java.awt.Color(204, 204, 204));
        bX.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bX.setText("x");
        bX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bXActionPerformed(evt);
            }
        });

        bDiv.setBackground(new java.awt.Color(204, 204, 204));
        bDiv.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bDiv.setText("/");
        bDiv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivActionPerformed(evt);
            }
        });

        bAdd.setBackground(new java.awt.Color(204, 204, 204));
        bAdd.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bAdd.setText("+");
        bAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bSous.setBackground(new java.awt.Color(204, 204, 204));
        bSous.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bSous.setText("-");
        bSous.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSousActionPerformed(evt);
            }
        });

        bAns.setBackground(new java.awt.Color(204, 204, 204));
        bAns.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bAns.setText("Ans");
        bAns.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bEgal.setBackground(new java.awt.Color(204, 204, 204));
        bEgal.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bEgal.setText("=");
        bEgal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEgal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEgalActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(102, 102, 0));
        jButton22.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        jButton22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton23.setBackground(new java.awt.Color(102, 102, 0));
        jButton23.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        jButton23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bX2.setBackground(new java.awt.Color(102, 102, 0));
        bX2.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bX2.setForeground(new java.awt.Color(255, 255, 255));
        bX2.setText("x²");
        bX2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bX2ActionPerformed(evt);
            }
        });

        bXn.setBackground(new java.awt.Color(102, 102, 0));
        bXn.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bXn.setForeground(new java.awt.Color(255, 255, 255));
        bXn.setText("x^");
        bXn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bXn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bXnActionPerformed(evt);
            }
        });

        bLog.setBackground(new java.awt.Color(102, 102, 0));
        bLog.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bLog.setForeground(new java.awt.Color(255, 255, 255));
        bLog.setText("Log");
        bLog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogActionPerformed(evt);
            }
        });

        bLn.setBackground(new java.awt.Color(102, 102, 0));
        bLn.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bLn.setForeground(new java.awt.Color(255, 255, 255));
        bLn.setText("Ln");
        bLn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLnActionPerformed(evt);
            }
        });

        bTan.setBackground(new java.awt.Color(102, 102, 0));
        bTan.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bTan.setForeground(new java.awt.Color(255, 255, 255));
        bTan.setText("Tan");
        bTan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTanActionPerformed(evt);
            }
        });

        bCos.setBackground(new java.awt.Color(102, 102, 0));
        bCos.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bCos.setForeground(new java.awt.Color(255, 255, 255));
        bCos.setText("Cos");
        bCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCosActionPerformed(evt);
            }
        });

        bSin.setBackground(new java.awt.Color(102, 102, 0));
        bSin.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bSin.setForeground(new java.awt.Color(255, 255, 255));
        bSin.setText("Sin");
        bSin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSinActionPerformed(evt);
            }
        });

        bParen1.setBackground(new java.awt.Color(102, 102, 0));
        bParen1.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bParen1.setForeground(new java.awt.Color(255, 255, 255));
        bParen1.setText(")");
        bParen1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bParen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParen1ActionPerformed(evt);
            }
        });

        bParen2.setBackground(new java.awt.Color(102, 102, 0));
        bParen2.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        bParen2.setForeground(new java.awt.Color(255, 255, 255));
        bParen2.setText("(");
        bParen2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bParen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParen2ActionPerformed(evt);
            }
        });

        jButton33.setBackground(new java.awt.Color(102, 102, 0));
        jButton33.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        jButton33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Source Code Pro Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CALCULATRICE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bVirg, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bDel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bAc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bX, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bSous, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bAns, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bEgal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bParen2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bParen1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bSin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bCos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bTan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Ecran, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bX2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bXn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bLog, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bLn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ecran, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bX2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bXn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bParen2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bParen1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSous, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVirg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAns, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEgal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(403, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EcranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EcranActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       // Ecran.setText(Ecran.getText()+"6");
        if (Ecran.getText().isEmpty()){
            num1=6;
            Ecran.setText(Ecran.getText()+"6");
        } else {
            num2=6;
            Ecran.setText(Ecran.getText()+"6");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
       // Ecran.setText(Ecran.getText()+"9");
       if (Ecran.getText().isEmpty()){
            num1=9;
            Ecran.setText(Ecran.getText()+"9");
        } else {
            num2=9;
            Ecran.setText(Ecran.getText()+"9");
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (Ecran.getText().isEmpty()){
            num1=8;
            Ecran.setText(Ecran.getText()+"8");
        } else {
            num2=8;
            Ecran.setText(Ecran.getText()+"8");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (Ecran.getText().isEmpty()){
            num1=7;
            Ecran.setText(Ecran.getText()+"7");
        } else {
            num2=7;
            Ecran.setText(Ecran.getText()+"7");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       if (Ecran.getText().isEmpty()){
            num1=4;
            Ecran.setText(Ecran.getText()+"4");
        } else {
            num2=4;
            Ecran.setText(Ecran.getText()+"4");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
         if (Ecran.getText().isEmpty()){
            num1=5;
            Ecran.setText(Ecran.getText()+"5");
        } else {
            num2=5;
            Ecran.setText(Ecran.getText()+"5");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
         if (Ecran.getText().isEmpty()){
            num1=1;
            Ecran.setText(Ecran.getText()+"1");
        } else {
            num2=1;
            Ecran.setText(Ecran.getText()+"1");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
         if (Ecran.getText().isEmpty()){
            num1=2;
            Ecran.setText(Ecran.getText()+"2");
        } else {
            num2=2;
            Ecran.setText(Ecran.getText()+"2");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (Ecran.getText().isEmpty()){
            num1=3;
            Ecran.setText(Ecran.getText()+"3");
        } else {
            num2=3;
            Ecran.setText(Ecran.getText()+"3");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
         if (Ecran.getText().isEmpty()){
            num1=0;
            Ecran.setText(Ecran.getText()+"0");
        } else {
            num2=0;
            Ecran.setText(Ecran.getText()+"0");
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        //num1=Double.parseDouble(Ecran.getText());
        op="+";
        Ecran.setText(Ecran.getText()+"+");
       // Ecran.setText("");
    }//GEN-LAST:event_bAddActionPerformed

    private void bXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXActionPerformed
        op="*";
        Ecran.setText(Ecran.getText()+"*");
    }//GEN-LAST:event_bXActionPerformed

    private void bDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivActionPerformed
        op="/";
        Ecran.setText(Ecran.getText()+"/");
    }//GEN-LAST:event_bDivActionPerformed

    private void bSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSousActionPerformed
        op="-";
        Ecran.setText(Ecran.getText()+"-");
    }//GEN-LAST:event_bSousActionPerformed

    private void bEgalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEgalActionPerformed
       //num2=Double.parseDouble(Ecran.getText());
        Ecran.setText("");
        
        switch(op){
            case "+":
                Ecran.setText(String.valueOf(num1 + num2));
                break; 
            case "-":
                Ecran.setText(String.valueOf(num1 - num2));
                break; 
            case "*":
                Ecran.setText(String.valueOf(num1 * num2));
                break; 
            case "/":
                Ecran.setText(String.valueOf(num1 / num2));
                break; 
            case "sin":
                Ecran.setText(String.valueOf(Math.sin(num2)));
                break;
            case "cos":
                Ecran.setText(String.valueOf(Math.cos(num2)));
                break;
            case "tan":
                Ecran.setText(String.valueOf(Math.tan(num2)));
                break;
            case "²":
                Ecran.setText(String.valueOf(Math.pow(num1,2)));
                break;
            case "^":
                Ecran.setText(String.valueOf(Math.pow(num1,num2)));
                break;
            case "log":
                Ecran.setText(String.valueOf(Math.log10(num2)));
                break;
            case "ln":
                Ecran.setText(String.valueOf(Math.log(num2)));
                break;
        }
    }//GEN-LAST:event_bEgalActionPerformed

    private void bAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcActionPerformed
        Ecran.setText("");
        num1=num2=0;
        op="";
    }//GEN-LAST:event_bAcActionPerformed

    private void bVirgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVirgActionPerformed
        Ecran.setText(Ecran.getText()+".");
    }//GEN-LAST:event_bVirgActionPerformed

    private void bSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSinActionPerformed
        //num1=Double.parseDouble(Ecran.getText());
        Ecran.setText("");
        op="sin";
        Ecran.setText(Ecran.getText()+"sin(");
        //Ecran.setText("");
    }//GEN-LAST:event_bSinActionPerformed

    private void bCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCosActionPerformed
        Ecran.setText("");
        op="cos";
        Ecran.setText(Ecran.getText()+"cos(");
    }//GEN-LAST:event_bCosActionPerformed

    private void bTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTanActionPerformed
        Ecran.setText("");
        op="tan";
        Ecran.setText(Ecran.getText()+"tan(");
    }//GEN-LAST:event_bTanActionPerformed

    private void bParen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParen1ActionPerformed
        Ecran.setText(Ecran.getText()+")");
    }//GEN-LAST:event_bParen1ActionPerformed

    private void bParen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParen2ActionPerformed
        Ecran.setText(Ecran.getText()+"(");
    }//GEN-LAST:event_bParen2ActionPerformed

    private void bX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bX2ActionPerformed
        op="²";
        Ecran.setText(Ecran.getText()+"²");
    }//GEN-LAST:event_bX2ActionPerformed

    private void bXnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXnActionPerformed
         op="^";
        Ecran.setText(Ecran.getText()+"^");
    }//GEN-LAST:event_bXnActionPerformed

    private void bLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogActionPerformed
        Ecran.setText("");
        op="log";
        Ecran.setText(Ecran.getText()+"log(");
    }//GEN-LAST:event_bLogActionPerformed

    private void bLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLnActionPerformed
        Ecran.setText("");
        op="ln";
        Ecran.setText(Ecran.getText()+"ln(");
    }//GEN-LAST:event_bLnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ecran;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bAc;
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bAns;
    private javax.swing.JButton bCos;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bDiv;
    private javax.swing.JButton bEgal;
    private javax.swing.JButton bLn;
    private javax.swing.JButton bLog;
    private javax.swing.JButton bParen1;
    private javax.swing.JButton bParen2;
    private javax.swing.JButton bSin;
    private javax.swing.JButton bSous;
    private javax.swing.JButton bTan;
    private javax.swing.JButton bVirg;
    private javax.swing.JButton bX;
    private javax.swing.JButton bX2;
    private javax.swing.JButton bXn;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
